#!/bin/sh /etc/rc.common

START=96

readonly SERVICE_FILE="/usr/bin/ip6neigh_service.sh"

errormsg() {
	local msg="Error: $1"
	>&2 echo "$msg"
	logger -t ip6neigh "$msg"
	exit 1
}

start() {
	pgrep -f ip6neigh_mon.sh >/dev/null && return 0
	
	[ -f "$SERVICE_FILE" ] || errormsg "The main script file $SERVICE_FILE is missing."

	SERVICE_DAEMONIZE=1
	service_start "$SERVICE_FILE" -s

	return 0
}

stop() {
	killall ip6neigh_mon.sh 2>/dev/null
	return 0
}

restart() {
	stop
	sleep 1
	start
	return 0
}
