#!/bin/sh /etc/rc.common

#ip6neigh init.d script

START=96

readonly VERSION="1.6.0"
readonly SBIN_PATH="/usr/sbin/"
readonly SERVICE_NAME="ip6neigh-svc.sh"
readonly SERVICE_SCRIPT="${SBIN_PATH}${SERVICE_NAME}"

errormsg() {
	local msg="Error: $1"
	>&2 echo "$msg"
	logger -t ip6neigh "$msg"
	exit 1
}

start() {
	pgrep -f "$SERVICE_NAME" >/dev/null && return 0
	
	[ -f "$SERVICE_SCRIPT" ] || errormsg "The main script file $SERVICE_SCRIPT is missing."

	local snoop=$(uci get ip6neigh.config.dad_snoop 2>/dev/null)

	SERVICE_DAEMONIZE=1
	
	service_start "$SERVICE_SCRIPT" -s
	[ "$snoop" = '1' ] && service_start "$SERVICE_SCRIPT" -n

	return 0
}

stop() {
	local ppid
	local cpid
	
	pgrep -f "$SERVICE_NAME" |
		while IFS= read -r ppid
		do
			pgrep -P "$ppid" |
				while IFS= read -r cpid
				do
					kill "$cpid" 2>/dev/null
				done
			kill "$ppid" 2>/dev/null
		done

	return 0
}

restart() {
	stop
	sleep 1
	start
	return 0
}
